###
GET localhost:8101/accounts

###
POST localhost:8101/create

###
GET localhost:8101/accounts

###
POST localhost:8101/account/2/credit/150

###
GET localhost:8101/account/3/amount

###
POST localhost:8101/account/2/transfer/1/50

###
POST localhost:8101/account/1/transfer/2/25

###
POST localhost:8101/account/2/debit/100/category3