###
GET localhost:8101/accounts

###
POST localhost:8101/create

###
GET localhost:8101/accounts

###
POST localhost:8101/account/1/credit/100

###
GET localhost:8101/account/1/amount

###
GET localhost:8101/account/2/amount

###
POST localhost:8101/account/2/transfer/1/50

###
POST localhost:8101/account/1/transfer/2/1


###
GET localhost:8080/categories

###
POST localhost:8101/account/1/debit/50/hard

###
POST localhost:8080/create/category/carshops/2

###
POST localhost:8101/account/1/debit/50/carshops